In [9]:
import pandas as pd
import numpy as np

In [10]:
df = pd.read_excel('Attendance_Productivity_AllMonths_2023_2026_V2.xlsx')

In [11]:
df

,AttendanceID,EmployeeID,Date,CheckInTime,CheckOutTime,ScheduledStartTime,ScheduledEndTime,TotalHoursWorked,OvertimeHours,AttendanceStatus,LateArrivalFlag,EarlyLogoutFlag,LeaveType,WorkMode,ProductivityScore,TaskCountCompleted,TargetTaskCount,BillableHours,NonBillableHours
0,1,1001,2023-01-02,09:00:00,16:30:00,09:00:00,17:00:00,8.14,0.14,Present,False,True,NaN,Hybrid,68.93,6,10,6.52,1.62
1,2,1002,2023-01-02,09:14:00,17:00:00,09:00:00,17:00:00,7.14,0.00,Present,True,False,NaN,Hybrid,68.75,13,10,6.4,0.74
2,3,1003,2023-01-02,09:21:00,17:00:00,09:00:00,17:00:00,8.08,0.08,Leave,True,False,Casual,Onsite,77.97,9,10,6.71,1.37
3,4,1004,2023-01-02,09:14:00,17:00:00,09:00:00,17:00:00,7.58,0.00,Present,True,False,NaN,Remote,68.61,10,10,5.65,1.93
4,5,1005,2023-01-02,09:28:00,17:00:00,09:00:00,17:00:00,7.58,0.00,Present,True,False,NaN,Remote,92.29,12,10,6.3,1.28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104395,104396,1096,2026-12-31,09:00:00,16:40:00,09:00:00,17:00:00,8.44,0.44,Present,False,True,NaN,Onsite,83.63,13,10,6.9,1.54
104396,104397,1097,2026-12-31,09:08:00,17:00:00,09:00:00,17:00:00,7.76,0.00,Leave,True,False,NaN,Onsite,77.07,10,10,5.72,2.04
104397,104398,1098,2026-12-31,09:20:00,17:00:00,09:00:00,17:00:00,7.53,0.00,Present,True,False,NaN,Onsite,93.7,9,10,6.78,0.75
104398,104399,1099,2026-12-31,09:00:00,17:00:00,09:00:00,17:00:00,7.37,0.00,Present,False,False,NaN,Onsite,95.68,15,10,6.53,0.84
104399,104400,1100,2026-12-31,09:00:00,17:00:00,09:00:00,17:00:00,8.42,0.42,Leave,False,False,NaN,Remote,60.17,15,10,6.86,1.56

In [12]:
updates = {
    'CheckInTime': np.nan, 'CheckOutTime': np.nan, 'WorkMode': np.nan,
    'TotalHoursWorked': 0, 'OvertimeHours': 0, 'BillableHours': 0, 
    'NonBillableHours': 0, 'ProductivityScore': 0, 'TaskCountCompleted': 0,
    'LateArrivalFlag': False, 'EarlyLogoutFlag': False
}

df.loc[df['AttendanceStatus'] == 'Leave', list(updates.keys())] = list(updates.values())

In [13]:
df = df[df['EmployeeID']<1051]

In [14]:
df = df[df['Date']< '2026-05-11']

In [15]:
df

,AttendanceID,EmployeeID,Date,CheckInTime,CheckOutTime,ScheduledStartTime,ScheduledEndTime,TotalHoursWorked,OvertimeHours,AttendanceStatus,LateArrivalFlag,EarlyLogoutFlag,LeaveType,WorkMode,ProductivityScore,TaskCountCompleted,TargetTaskCount,BillableHours,NonBillableHours
0,1,1001,2023-01-02,09:00:00,16:30:00,09:00:00,17:00:00,8.14,0.14,Present,False,True,NaN,Hybrid,68.93,6,10,6.52,1.62
1,2,1002,2023-01-02,09:14:00,17:00:00,09:00:00,17:00:00,7.14,0.00,Present,True,False,NaN,Hybrid,68.75,13,10,6.4,0.74
2,3,1003,2023-01-02,NaN,NaN,09:00:00,17:00:00,0.00,0.00,Leave,False,False,Casual,NaN,0,0,10,0,0.00
3,4,1004,2023-01-02,09:14:00,17:00:00,09:00:00,17:00:00,7.58,0.00,Present,True,False,NaN,Remote,68.61,10,10,5.65,1.93
4,5,1005,2023-01-02,09:28:00,17:00:00,09:00:00,17:00:00,7.58,0.00,Present,True,False,NaN,Remote,92.29,12,10,6.3,1.28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87445,87446,1046,2026-05-08,09:00:00,17:00:00,09:00:00,17:00:00,7.22,0.00,Present,False,False,NaN,Hybrid,61.13,12,10,6.31,0.91
87446,87447,1047,2026-05-08,09:00:00,17:00:00,09:00:00,17:00:00,7.50,0.00,Present,False,False,NaN,Onsite,98.88,10,10,6.37,1.13
87447,87448,1048,2026-05-08,09:10:00,17:00:00,09:00:00,17:00:00,8.38,0.38,Present,True,False,NaN,Hybrid,66.53,12,10,5.54,2.84
87448,87449,1049,2026-05-08,NaN,NaN,09:00:00,17:00:00,0.00,0.00,Leave,False,False,Sick,NaN,0,0,10,0,0.00
87449,87450,1050,2026-05-08,09:00:00,17:00:00,09:00:00,17:00:00,7.75,0.00,Present,False,False,NaN,Hybrid,74.41,13,10,6.49,1.26

In [16]:
df.to_excel('attendance.xlsx')